say-hello :
  image : alpine:latest
  script:
    - echo 'hello world !!'
    - ls
    - /usr/bin/scp usersspringboot/target/usersspringboot-0.0.1-SNAPSHOT.jar etudiant@192.168.75.26:~/
    - send -- "$env(USER_PASSWORD_VM)\r"
